# ----------------------- #
#      Main Configs       #
# ----------------------- #

<<<<<<< HEAD
url: http://lkbgift.github.com
title: Leonard Kiyoshi Bogdonoff
subtitle: Prespectives of a twenty something experiencing the world
author: Leonard Kiyoshi Bogdonoff
simple_search: 
description: Blog about web development, trends, education, and experiencing the world.
=======
url: http://rememberlenny.github.io
title: Remember Lenny
subtitle: Front-end development, startups, and culture.
author: Leonard Bogdonoff
simple_search: http://google.com/search
description: Leonard Bogdonoff's blog about front-end development, startups, and culture.
>>>>>>> f0d868f464e0458278905dbb968a46b4b6913b0b

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: lkbgift@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
<<<<<<< HEAD
default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html]
=======
# default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html]
>>>>>>> f0d868f464e0458278905dbb968a46b4b6913b0b

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
<<<<<<< HEAD
github_user: lkbgift
github_repo_count: 0
=======
github_user: rememberlenny
github_repo_count: 1
>>>>>>> f0d868f464e0458278905dbb968a46b4b6913b0b
github_show_profile_link: true
github_skip_forks: true

# Twitter
<<<<<<< HEAD
twitter_user: lkbcc
twitter_tweet_count: 4
=======
twitter_user: rememberlenny
twitter_tweet_count: 1
>>>>>>> f0d868f464e0458278905dbb968a46b4b6913b0b
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 107599061568558533958
googleplus_hidden: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: lkbcc
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-36960596-1

# Facebook Like
facebook_like: false

